name: ave_anomaly_detection_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.0
  - pandas=1.5.1
  - scipy=1.10.1
  - tensorflow=2.17.0
  - keras=3.5.0
  - matplotlib=3.6.2
  - seaborn=0.12.2
